name: Happy Bottom Bikes
favicon: null
layout_spectrum: 0.91708
typography_spectrum: 0.33923460403457284
title: Home Page
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8c8d1'
    - '#170c12'
    - '#60475d'
    - '#907996'
    - '#167b0b'
  brandStrength: 0.625
  lightness: 0.9350590892136097
  saturation: 0.5799053288064897
  rhythmicContrast: 0.6824086657725275
purpose: []
